export const employeeCategories = [
    'MBA',
    'Software Engineers',
    'Mechanical Engineer',
    'Chemical Engineer',
    'Technical Staff',
    'Non-Technical Staff',
    'Blue Collar - Skilled',
    'Blue Collar - Unskilled',
    'ITI Holder',
    'Back Office',
    'Promoters',
    'Supervisors',
    'Marketing Staff',
    'Collection Staff',
    'Event Management',
    'Trainee',
    'Apprentice',
    'Nurses',
    'Technical Staff',
    'Ward Boy',
    'PCA (Patient Care Assistant)',
    'Janitors',
    'Data Entry Operators',
    'Electricians',
    'Plumber',
    'Driver',
    'Liftman',
    'Housekeeper',
    'Facility Executive',
    'Lab Technician'
];

